aws:
  region: us-east-1
  bucket: bucket-test013
  topic: arn:aws:sns:us-east-1:430118847461:s3-operation-alerts

  sqs:
    queue-url: https://sqs.us-east-1.amazonaws.com/430118847461/MinhaFilaPrincipal
    dlq-url: https://sqs.us-east-1.amazonaws.com/430118847461/MinhaDLQ
    region: us-east-1

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"